const { request, BASE_URL } = require('../../utils/request.js');

const AUTO_GEN_STORAGE_KEY = 'autoCertGenerated_v1';

const getStudentNo = () => wx.getStorageSync('studentNo') || wx.getStorageSync('account');
const isAutoCertType = (t) => t === '党员证明' || t === '团员证明';

const formatTime = (d = new Date()) => {
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
};

Page({
  data: {
    autoCertTypes: ['党员证明', '团员证明'],
    autoTypeIndex: 0,
    approvalCertTypes: ['在校证明', '请假条', '用章申请'],
    approvalTypeIndex: 0,
    approvalReason: '',
    approvalStartDate: '',
    approvalEndDate: '',
    autoGeneratedList: [],
    approvalHistoryList: [],
    expandedCertId: null,
  },

  onShow() {
    this.loadAutoGenerated();
    this.fetchHistory();
  },

  bindAutoTypeChange(e) {
    const idx = Number(e.detail.value);
    this.setData({ autoTypeIndex: Number.isFinite(idx) ? idx : 0 });
  },

  bindApprovalTypeChange(e) {
    const idx = Number(e.detail.value);
    this.setData({ approvalTypeIndex: Number.isFinite(idx) ? idx : 0 });
  },

  toggleReason(e) {
    const id = e.currentTarget.dataset.id;
    this.setData({ expandedCertId: this.data.expandedCertId === id ? null : id });
  },

  onApprovalReasonInput(e) {
    this.setData({ approvalReason: e.detail.value });
  },

  onApprovalStartDateChange(e) {
    this.setData({ approvalStartDate: e.detail.value });
  },

  onApprovalEndDateChange(e) {
    this.setData({ approvalEndDate: e.detail.value });
  },

  loadAutoGenerated() {
    try {
      const list = wx.getStorageSync(AUTO_GEN_STORAGE_KEY);
      const arr = Array.isArray(list) ? list : [];
      this.setData({ autoGeneratedList: arr });
    } catch (e) {
      this.setData({ autoGeneratedList: [] });
    }
  },

  appendAutoGenerated(certificateType) {
    const now = new Date();
    const item = {
      id: `${now.getTime()}`,
      certificateType,
      createdAt: formatTime(now)
    };
    const next = [item].concat(this.data.autoGeneratedList || []);
    this.setData({ autoGeneratedList: next });
    try {
      wx.setStorageSync(AUTO_GEN_STORAGE_KEY, next.slice(0, 50));
    } catch (e) {}
  },

  fetchHistory() {
    request('/api/student/certificate/history', 'GET', { studentNo: getStudentNo() })
      .then(res => {
        const all = Array.isArray(res)
          ? res.map(item => ({
              id: item.id,
              certificateType: item.certificateType || item.certificatetype,
              applyStatus: item.applyStatus || item.applystatus,
              extraData: item.extraData || item.extradata || '未填写申请事由',
              createdAt: item.createdAt || item.createdat,
              fileId: item.fileId || item.fileid
            }))
          : [];
        const approvalHistoryList = all.filter(i => !isAutoCertType(i.certificateType));
        this.setData({ approvalHistoryList });
      });
  },

  submitAutoCert() {
    const studentNo = getStudentNo();
    const certificateType = this.data.autoCertTypes[this.data.autoTypeIndex];
    if (!studentNo) return wx.showToast({ title: '未获取到学号', icon: 'none' });
    if (!certificateType) return wx.showToast({ title: '请选择证明类型', icon: 'none' });

    wx.showLoading({ title: '生成中...' });
    const url = `${BASE_URL}/api/student/certificate/auto/download?studentNo=${encodeURIComponent(studentNo)}&certificateType=${encodeURIComponent(certificateType)}`;
    wx.downloadFile({
      url,
      header: { Authorization: wx.getStorageSync('token') },
      success: (res) => {
        if (res.statusCode === 200) {
          wx.openDocument({ filePath: res.tempFilePath, showMenu: true });
          this.appendAutoGenerated(certificateType);
          wx.showToast({ title: '已生成', icon: 'success' });
          this.setData({ expandedCertId: null });
        } else {
          wx.showToast({ title: '生成失败', icon: 'none' });
        }
      },
      fail: (err) => {
        wx.showToast({ title: err.message || err.errMsg || '生成失败', icon: 'none' });
      },
      complete: () => wx.hideLoading()
    });
  },

  downloadAutoCert(e) {
    const certificateType = e.currentTarget.dataset.type;
    const studentNo = getStudentNo();
    if (!studentNo || !certificateType) return;
    wx.showLoading({ title: '正在获取文件...' });
    wx.downloadFile({
      url: `${BASE_URL}/api/student/certificate/auto/download?studentNo=${encodeURIComponent(studentNo)}&certificateType=${encodeURIComponent(certificateType)}`,
      header: { Authorization: wx.getStorageSync('token') },
      success: (res) => {
        if (res.statusCode === 200) {
          wx.openDocument({ filePath: res.tempFilePath, showMenu: true });
        } else {
          wx.showToast({ title: '文件下载失败', icon: 'none' });
        }
      },
      complete: () => wx.hideLoading()
    });
  },

  submitApprovalCert() {
    wx.showLoading({ title: '提交申请中...' });
    const payload = {
      reason: this.data.approvalReason || '无',
      startAt: this.data.approvalStartDate || '',
      endAt: this.data.approvalEndDate || ''
    };
    request('/api/student/certificate/apply', 'POST', {
      studentNo: getStudentNo(),
      certificateType: this.data.approvalCertTypes[this.data.approvalTypeIndex],
      extraData: JSON.stringify(payload)
    }).then(() => {
      wx.hideLoading();
      wx.showToast({ title: '已提交', icon: 'success' });
      this.setData({ approvalReason: '', approvalStartDate: '', approvalEndDate: '', expandedCertId: null });
      this.fetchHistory();
    }).catch(err => {
      wx.hideLoading();
      wx.showToast({ title: err.message || err.errMsg || '提交失败', icon: 'none' });
    });
  },

  downloadCert(e) {
    const fileId = e.currentTarget.dataset.fileid;
    wx.showLoading({ title: '正在获取文件...' });
    wx.downloadFile({
      url: `${BASE_URL}/api/file/download/${fileId}`,
      header: { Authorization: wx.getStorageSync('token') },
      success: (res) => {
        if (res.statusCode === 200) {
          wx.openDocument({ filePath: res.tempFilePath, showMenu: true });
        } else {
          wx.showToast({ title: '文件下载失败', icon: 'none' });
        }
      },
      complete: () => wx.hideLoading()
    });
  }
});
