package com.college.student_service_platform.service;

import com.college.student_service_platform.dto.ApprovalTaskItem;
import com.college.student_service_platform.dto.CertificateApplyDetail;
import com.college.student_service_platform.dto.CertificateApplyItem;
import com.college.student_service_platform.dto.CertificateApplySubmitRequest;
import com.college.student_service_platform.dto.CertificateDecisionRequest;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.pdf.BaseFont;
import fr.opensagres.poi.xwpf.converter.pdf.PdfConverter;
import fr.opensagres.poi.xwpf.converter.pdf.PdfOptions;
import fr.opensagres.xdocreport.itext.extension.font.IFontProvider;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.openxmlformats.schemas.wordprocessingml.x2006.main.CTR;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.ByteArrayOutputStream;
import java.awt.Color;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicLong;

@Service
public class CertificateApplyService {

    private final JdbcTemplate jdbcTemplate;
    private final AtomicLong idSeq = new AtomicLong(System.currentTimeMillis());

    @Value("${file.upload-dir}")
    private String uploadDir;

    public CertificateApplyService(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Transactional
    public Long submit(CertificateApplySubmitRequest request) {
        if (request == null) {
            throw new IllegalArgumentException("请求不能为空");
        }
        String studentNo = normalize(request.getStudentNo());
        String certificateType = normalize(request.getCertificateType());
        if (studentNo.isEmpty()) {
            throw new IllegalArgumentException("学号不能为空");
        }
        if (certificateType.isEmpty()) {
            throw new IllegalArgumentException("证明类型不能为空");
        }
        String extraData = request.getExtraData() == null ? null : request.getExtraData().trim();

        Timestamp now = Timestamp.valueOf(LocalDateTime.now());
        Long applyId = idSeq.incrementAndGet();
        if (isAutoGeneratedCertificate(certificateType)) {
            jdbcTemplate.update(
                    """
                            INSERT INTO t_certificate_apply
                            (id, student_no, certificate_type, apply_status, extra_data, file_id, created_at, updated_at)
                            VALUES (?, ?, ?, '已生成', ?, NULL, ?, ?)
                            """,
                    applyId,
                    studentNo,
                    certificateType,
                    extraData,
                    now,
                    now
            );

            CertificateApplyItem apply = new CertificateApplyItem();
            apply.setId(applyId);
            apply.setStudentNo(studentNo);
            apply.setCertificateType(certificateType);
            apply.setApplyStatus("已生成");
            apply.setExtraData(extraData);

            Long fileId = generateCertificateFile(apply, now);
            jdbcTemplate.update(
                    """
                            UPDATE t_certificate_apply
                            SET file_id = ?, updated_at = ?
                            WHERE id = ?
                            """,
                    fileId,
                    now,
                    applyId
            );
            return applyId;
        }

        jdbcTemplate.update(
                """
                        INSERT INTO t_certificate_apply
                        (id, student_no, certificate_type, apply_status, extra_data, file_id, created_at, updated_at)
                        VALUES (?, ?, ?, '待审核', ?, NULL, ?, ?)
                        """,
                applyId,
                studentNo,
                certificateType,
                extraData,
                now,
                now
        );

        Long taskId = idSeq.incrementAndGet();
        jdbcTemplate.update(
                """
                        INSERT INTO t_approval_task
                        (id, apply_id, node_order, approver_id, approver_name, approval_status, opinion, handled_at, created_at, updated_at)
                        VALUES (?, ?, 1, NULL, NULL, '待处理', NULL, NULL, ?, ?)
                        """,
                taskId,
                applyId,
                now,
                now
        );

        return applyId;
    }

    public byte[] generateAutoCertificatePdf(String studentNo, String certificateType) {
        String stu = normalize(studentNo);
        String type = normalize(certificateType);
        if (stu.isEmpty()) {
            throw new IllegalArgumentException("学号不能为空");
        }
        if (type.isEmpty()) {
            throw new IllegalArgumentException("证明类型不能为空");
        }
        if (!isAutoGeneratedCertificate(type)) {
            throw new IllegalArgumentException("该证明类型不支持自动生成");
        }

        Map<String, Object> studentData = jdbcTemplate.query(
                """
                        SELECT s.student_no,
                               s.name,
                               s.id_card_no,
                               s.class_name,
                               s.major,
                               s.grade,
                               s.education_level,
                               s.political_status,
                               p.join_league_date,
                               p.league_member_no,
                               p.join_party_date,
                               p.party_branch_name,
                               u.id AS user_id
                        FROM t_student s
                        LEFT JOIN t_student_political_info p ON p.student_no = s.student_no
                        LEFT JOIN t_user u ON u.student_no = s.student_no AND u.role_code = 'student'
                        WHERE s.student_no = ?
                        """,
                rs -> {
                    if (!rs.next()) {
                        throw new IllegalArgumentException("未找到学生基础信息");
                    }
                    Map<String, Object> data = new java.util.LinkedHashMap<>();
                    data.put("studentNo", rs.getString("student_no"));
                    data.put("name", blankToEmpty(rs.getString("name")));
                    data.put("idCardNo", blankToEmpty(rs.getString("id_card_no")));
                    data.put("className", blankToEmpty(rs.getString("class_name")));
                    data.put("major", blankToEmpty(rs.getString("major")));
                    data.put("grade", blankToEmpty(rs.getString("grade")));
                    data.put("educationLevel", blankToEmpty(rs.getString("education_level")));
                    data.put("politicalStatus", blankToEmpty(rs.getString("political_status")));
                    data.put("joinLeagueDate", formatDate(rs.getDate("join_league_date") == null ? null : rs.getDate("join_league_date").toLocalDate()));
                    data.put("leagueMemberNo", blankToEmpty(rs.getString("league_member_no")));
                    data.put("joinPartyDate", formatDate(rs.getDate("join_party_date") == null ? null : rs.getDate("join_party_date").toLocalDate()));
                    data.put("partyBranchName", blankToEmpty(rs.getString("party_branch_name")));
                    data.put("userId", rs.getObject("user_id") == null ? null : rs.getLong("user_id"));
                    return data;
                },
                stu
        );

        LocalDate issueDate = LocalDate.now();
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            renderTemplateToPdf(resolveTemplatePath(type), type, studentData, issueDate, out);
            return out.toByteArray();
        } catch (IOException e) {
            throw new IllegalStateException("生成证明文件失败: " + e.getMessage(), e);
        }
    }

    public byte[] generateAutoCertificateDocx(String studentNo, String certificateType) {
        String stu = normalize(studentNo);
        String type = normalize(certificateType);
        if (stu.isEmpty()) {
            throw new IllegalArgumentException("学号不能为空");
        }
        if (type.isEmpty()) {
            throw new IllegalArgumentException("证明类型不能为空");
        }
        if (!isAutoGeneratedCertificate(type)) {
            throw new IllegalArgumentException("该证明类型不支持自动生成");
        }

        Map<String, Object> studentData = jdbcTemplate.query(
                """
                        SELECT s.student_no,
                               s.name,
                               s.id_card_no,
                               s.class_name,
                               s.major,
                               s.grade,
                               s.education_level,
                               s.political_status,
                               p.join_league_date,
                               p.league_member_no,
                               p.join_party_date,
                               p.party_branch_name,
                               u.id AS user_id
                        FROM t_student s
                        LEFT JOIN t_student_political_info p ON p.student_no = s.student_no
                        LEFT JOIN t_user u ON u.student_no = s.student_no AND u.role_code = 'student'
                        WHERE s.student_no = ?
                        """,
                rs -> {
                    if (!rs.next()) {
                        throw new IllegalArgumentException("未找到学生基础信息");
                    }
                    Map<String, Object> data = new java.util.LinkedHashMap<>();
                    data.put("studentNo", rs.getString("student_no"));
                    data.put("name", blankToEmpty(rs.getString("name")));
                    data.put("idCardNo", blankToEmpty(rs.getString("id_card_no")));
                    data.put("className", blankToEmpty(rs.getString("class_name")));
                    data.put("major", blankToEmpty(rs.getString("major")));
                    data.put("grade", blankToEmpty(rs.getString("grade")));
                    data.put("educationLevel", blankToEmpty(rs.getString("education_level")));
                    data.put("politicalStatus", blankToEmpty(rs.getString("political_status")));
                    data.put("joinLeagueDate", formatDate(rs.getDate("join_league_date") == null ? null : rs.getDate("join_league_date").toLocalDate()));
                    data.put("leagueMemberNo", blankToEmpty(rs.getString("league_member_no")));
                    data.put("joinPartyDate", formatDate(rs.getDate("join_party_date") == null ? null : rs.getDate("join_party_date").toLocalDate()));
                    data.put("partyBranchName", blankToEmpty(rs.getString("party_branch_name")));
                    data.put("userId", rs.getObject("user_id") == null ? null : rs.getLong("user_id"));
                    return data;
                },
                stu
        );

        LocalDate issueDate = LocalDate.now();
        String templatePath = resolveTemplatePath(type);
        ClassPathResource resource = new ClassPathResource(templatePath);
        if (!resource.exists()) {
            throw new IllegalArgumentException("模板文件不存在: " + templatePath);
        }
        try (InputStream inputStream = resource.getInputStream();
             XWPFDocument document = new XWPFDocument(inputStream);
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            for (XWPFParagraph paragraph : document.getParagraphs()) {
                replaceInParagraph(paragraph, type, studentData, issueDate);
            }
            document.write(out);
            return out.toByteArray();
        } catch (IOException e) {
            throw new IllegalStateException("生成证明文件失败: " + e.getMessage(), e);
        }
    }

    public List<CertificateApplyItem> list(String status, String keyword) {
        String s = normalize(status);
        String k = normalize(keyword).toLowerCase();
        boolean hasStatus = !s.isEmpty();
        boolean hasKeyword = !k.isEmpty();

        String sql = """
                SELECT a.id,
                       TRIM(a.student_no) AS student_no,
                       s.name AS student_name,
                       s.class_name AS class_name,
                       a.certificate_type,
                       a.apply_status,
                       a.extra_data,
                       a.file_id,
                       a.created_at,
                       a.updated_at,
                       (
                           SELECT x.approver_name
                           FROM t_approval_task x
                           WHERE x.apply_id = a.id
                           ORDER BY x.node_order DESC
                           LIMIT 1
                       ) AS last_approver_name,
                       (
                           SELECT x.approval_status
                           FROM t_approval_task x
                           WHERE x.apply_id = a.id
                           ORDER BY x.node_order DESC
                           LIMIT 1
                       ) AS last_approval_status,
                       (
                           SELECT x.opinion
                           FROM t_approval_task x
                           WHERE x.apply_id = a.id
                           ORDER BY x.node_order DESC
                           LIMIT 1
                       ) AS last_opinion,
                       (
                           SELECT x.handled_at
                           FROM t_approval_task x
                           WHERE x.apply_id = a.id
                           ORDER BY x.node_order DESC
                           LIMIT 1
                       ) AS last_handled_at
                FROM t_certificate_apply a
                LEFT JOIN t_student s ON s.student_no = TRIM(a.student_no)
                """;

        List<Object> args = new ArrayList<>();
        List<String> wheres = new ArrayList<>();
        if (hasStatus) {
            wheres.add("a.apply_status = ?");
            args.add(s);
        }
        if (hasKeyword) {
            wheres.add("(LOWER(TRIM(a.student_no)) LIKE ? OR LOWER(COALESCE(s.name, '')) LIKE ? OR LOWER(COALESCE(s.class_name, '')) LIKE ? OR LOWER(a.certificate_type) LIKE ? OR LOWER(COALESCE(a.extra_data, '')) LIKE ?)");
            String like = "%" + k + "%";
            args.add(like);
            args.add(like);
            args.add(like);
            args.add(like);
            args.add(like);
        }
        if (!wheres.isEmpty()) {
            sql += " WHERE " + String.join(" AND ", wheres);
        }
        sql += " ORDER BY a.created_at DESC";

        return jdbcTemplate.query(sql, args.toArray(), (rs, rowNum) -> {
            CertificateApplyItem item = new CertificateApplyItem();
            item.setId(rs.getLong("id"));
            item.setStudentNo(rs.getString("student_no"));
            String studentName = rs.getString("student_name");
            item.setStudentName(studentName);
            item.setName(studentName);
            item.setClassName(rs.getString("class_name"));
            item.setCertificateType(rs.getString("certificate_type"));
            item.setApplyStatus(rs.getString("apply_status"));
            item.setExtraData(rs.getString("extra_data"));
            long fileId = rs.getLong("file_id");
            item.setFileId(rs.wasNull() ? null : fileId);
            Timestamp createdAt = rs.getTimestamp("created_at");
            Timestamp updatedAt = rs.getTimestamp("updated_at");
            if (createdAt != null) item.setCreatedAt(createdAt.toLocalDateTime());
            if (updatedAt != null) item.setUpdatedAt(updatedAt.toLocalDateTime());

            item.setLastApproverName(rs.getString("last_approver_name"));
            item.setLastApprovalStatus(rs.getString("last_approval_status"));
            item.setLastOpinion(rs.getString("last_opinion"));
            Timestamp lastHandledAt = rs.getTimestamp("last_handled_at");
            if (lastHandledAt != null) item.setLastHandledAt(lastHandledAt.toLocalDateTime());
            return item;
        });
    }

    public CertificateApplyDetail detail(Long applyId) {
        if (applyId == null) {
            throw new IllegalArgumentException("申请ID不能为空");
        }
        CertificateApplyItem apply = getApplyById(applyId);
        List<ApprovalTaskItem> tasks = listTasks(applyId);
        CertificateApplyDetail detail = new CertificateApplyDetail();
        detail.setApply(apply);
        detail.setTasks(tasks);
        return detail;
    }

    @Transactional
    public void decide(Long applyId, CertificateDecisionRequest request, Long approverId, String approverName) {
        if (applyId == null) {
            throw new IllegalArgumentException("申请ID不能为空");
        }
        if (request == null) {
            throw new IllegalArgumentException("请求不能为空");
        }
        String decision = normalize(request.getDecision()).toLowerCase();
        String opinion = normalize(request.getOpinion());
        if (opinion.isEmpty()) {
            throw new IllegalArgumentException("审批意见不能为空");
        }

        String applyStatus;
        String approvalStatus;
        if (decision.equals("approved") || decision.equals("pass") || decision.equals("通过") || decision.equals("已通过")) {
            applyStatus = "已通过";
            approvalStatus = "已通过";
        } else if (decision.equals("rejected") || decision.equals("reject") || decision.equals("驳回") || decision.equals("已驳回")) {
            applyStatus = "已驳回";
            approvalStatus = "已驳回";
        } else {
            throw new IllegalArgumentException("不支持的审批结果");
        }

        CertificateApplyItem existing = getApplyById(applyId);
        if (!"待审核".equals(normalize(existing.getApplyStatus()))) {
            throw new IllegalArgumentException("该申请已处理");
        }

        Timestamp now = Timestamp.valueOf(LocalDateTime.now());
        Long generatedFileId = null;

        Long taskId = jdbcTemplate.query(
                """
                        SELECT id
                        FROM t_approval_task
                        WHERE apply_id = ? AND approval_status = '待处理'
                        ORDER BY node_order ASC
                        """,
                rs -> rs.next() ? rs.getLong("id") : null,
                applyId
        );

        if (taskId != null) {
            jdbcTemplate.update(
                    """
                            UPDATE t_approval_task
                            SET approver_id = ?, approver_name = ?, approval_status = ?, opinion = ?, handled_at = ?, updated_at = ?
                            WHERE id = ?
                            """,
                    approverId,
                    approverName,
                    approvalStatus,
                    opinion,
                    now,
                    now,
                    taskId
            );
        } else {
            Integer maxOrder = jdbcTemplate.queryForObject(
                    "SELECT COALESCE(MAX(node_order), 0) FROM t_approval_task WHERE apply_id = ?",
                    Integer.class,
                    applyId
            );
            int nextOrder = (maxOrder == null ? 0 : maxOrder) + 1;
            Long newTaskId = idSeq.incrementAndGet();
            jdbcTemplate.update(
                    """
                            INSERT INTO t_approval_task
                            (id, apply_id, node_order, approver_id, approver_name, approval_status, opinion, handled_at, created_at, updated_at)
                            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                            """,
                    newTaskId,
                    applyId,
                    nextOrder,
                    approverId,
                    approverName,
                    approvalStatus,
                    opinion,
                    now,
                    now,
                    now
            );
        }

        if ("已通过".equals(applyStatus)) {
            if (isAutoGeneratedCertificate(existing.getCertificateType())) {
                generatedFileId = generateCertificateFile(existing, now);
            } else {
                generatedFileId = null;
            }
        }

        jdbcTemplate.update(
                """
                        UPDATE t_certificate_apply
                        SET apply_status = ?, file_id = ?, updated_at = ?
                        WHERE id = ?
                        """,
                applyStatus,
                generatedFileId,
                now,
                applyId
        );
    }

    @Transactional
    public void delete(Long applyId) {
        if (applyId == null) return;
        jdbcTemplate.update("DELETE FROM t_approval_task WHERE apply_id = ?", applyId);
        jdbcTemplate.update("DELETE FROM t_certificate_apply WHERE id = ?", applyId);
    }

    private CertificateApplyItem getApplyById(Long applyId) {
        String sql = """
                SELECT a.id,
                       TRIM(a.student_no) AS student_no,
                       s.name AS student_name,
                       s.class_name AS class_name,
                       a.certificate_type,
                       a.apply_status,
                       a.extra_data,
                       a.file_id,
                       a.created_at,
                       a.updated_at,
                       (
                           SELECT x.approver_name
                           FROM t_approval_task x
                           WHERE x.apply_id = a.id
                           ORDER BY x.node_order DESC
                           LIMIT 1
                       ) AS last_approver_name,
                       (
                           SELECT x.approval_status
                           FROM t_approval_task x
                           WHERE x.apply_id = a.id
                           ORDER BY x.node_order DESC
                           LIMIT 1
                       ) AS last_approval_status,
                       (
                           SELECT x.opinion
                           FROM t_approval_task x
                           WHERE x.apply_id = a.id
                           ORDER BY x.node_order DESC
                           LIMIT 1
                       ) AS last_opinion,
                       (
                           SELECT x.handled_at
                           FROM t_approval_task x
                           WHERE x.apply_id = a.id
                           ORDER BY x.node_order DESC
                           LIMIT 1
                       ) AS last_handled_at
                FROM t_certificate_apply a
                LEFT JOIN t_student s ON s.student_no = TRIM(a.student_no)
                WHERE a.id = ?
                """;
        return jdbcTemplate.query(sql, rs -> {
            if (!rs.next()) {
                throw new IllegalArgumentException("申请不存在");
            }
            CertificateApplyItem item = new CertificateApplyItem();
            item.setId(rs.getLong("id"));
            item.setStudentNo(rs.getString("student_no"));
            String studentName = rs.getString("student_name");
            item.setStudentName(studentName);
            item.setName(studentName);
            item.setClassName(rs.getString("class_name"));
            item.setCertificateType(rs.getString("certificate_type"));
            item.setApplyStatus(rs.getString("apply_status"));
            item.setExtraData(rs.getString("extra_data"));
            long fileId = rs.getLong("file_id");
            item.setFileId(rs.wasNull() ? null : fileId);
            Timestamp createdAt = rs.getTimestamp("created_at");
            Timestamp updatedAt = rs.getTimestamp("updated_at");
            if (createdAt != null) item.setCreatedAt(createdAt.toLocalDateTime());
            if (updatedAt != null) item.setUpdatedAt(updatedAt.toLocalDateTime());
            item.setLastApproverName(rs.getString("last_approver_name"));
            item.setLastApprovalStatus(rs.getString("last_approval_status"));
            item.setLastOpinion(rs.getString("last_opinion"));
            Timestamp lastHandledAt = rs.getTimestamp("last_handled_at");
            if (lastHandledAt != null) item.setLastHandledAt(lastHandledAt.toLocalDateTime());
            return item;
        }, applyId);
    }

    private List<ApprovalTaskItem> listTasks(Long applyId) {
        String sql = """
                SELECT id, apply_id, node_order, approver_id, approver_name, approval_status, opinion, handled_at, created_at, updated_at
                FROM t_approval_task
                WHERE apply_id = ?
                ORDER BY node_order ASC, created_at ASC
                """;

        return jdbcTemplate.query(sql, (rs, rowNum) -> {
            ApprovalTaskItem item = new ApprovalTaskItem();
            item.setId(rs.getLong("id"));
            item.setApplyId(rs.getLong("apply_id"));
            item.setNodeOrder(rs.getInt("node_order"));
            long approverId = rs.getLong("approver_id");
            item.setApproverId(rs.wasNull() ? null : approverId);
            item.setApproverName(rs.getString("approver_name"));
            item.setApprovalStatus(rs.getString("approval_status"));
            item.setOpinion(rs.getString("opinion"));
            Timestamp handledAt = rs.getTimestamp("handled_at");
            if (handledAt != null) item.setHandledAt(handledAt.toLocalDateTime());
            Timestamp createdAt = rs.getTimestamp("created_at");
            Timestamp updatedAt = rs.getTimestamp("updated_at");
            if (createdAt != null) item.setCreatedAt(createdAt.toLocalDateTime());
            if (updatedAt != null) item.setUpdatedAt(updatedAt.toLocalDateTime());
            return item;
        }, applyId);
    }

    private Long generateCertificateFile(CertificateApplyItem apply, Timestamp now) {
        Map<String, Object> studentData = jdbcTemplate.query(
                """
                        SELECT s.student_no,
                               s.name,
                               s.id_card_no,
                               s.class_name,
                               s.major,
                               s.grade,
                               s.education_level,
                               s.political_status,
                               p.join_league_date,
                               p.league_member_no,
                               p.join_party_date,
                               p.party_branch_name,
                               u.id AS user_id
                        FROM t_student s
                        LEFT JOIN t_student_political_info p ON p.student_no = s.student_no
                        LEFT JOIN t_user u ON u.student_no = s.student_no AND u.role_code = 'student'
                        WHERE s.student_no = ?
                        """,
                rs -> {
                    if (!rs.next()) {
                        throw new IllegalArgumentException("未找到学生基础信息");
                    }
                    Map<String, Object> data = new java.util.LinkedHashMap<>();
                    data.put("studentNo", rs.getString("student_no"));
                    data.put("name", blankToEmpty(rs.getString("name")));
                    data.put("idCardNo", blankToEmpty(rs.getString("id_card_no")));
                    data.put("className", blankToEmpty(rs.getString("class_name")));
                    data.put("major", blankToEmpty(rs.getString("major")));
                    data.put("grade", blankToEmpty(rs.getString("grade")));
                    data.put("educationLevel", blankToEmpty(rs.getString("education_level")));
                    data.put("politicalStatus", blankToEmpty(rs.getString("political_status")));
                    data.put("joinLeagueDate", formatDate(rs.getDate("join_league_date") == null ? null : rs.getDate("join_league_date").toLocalDate()));
                    data.put("leagueMemberNo", blankToEmpty(rs.getString("league_member_no")));
                    data.put("joinPartyDate", formatDate(rs.getDate("join_party_date") == null ? null : rs.getDate("join_party_date").toLocalDate()));
                    data.put("partyBranchName", blankToEmpty(rs.getString("party_branch_name")));
                    data.put("userId", rs.getObject("user_id") == null ? null : rs.getLong("user_id"));
                    return data;
                },
                apply.getStudentNo()
        );

        String certificateType = normalize(apply.getCertificateType());

        try {
            Path uploadPath = Paths.get(uploadDir).toAbsolutePath().normalize();
            Files.createDirectories(uploadPath);

            String originalName = safeFilePart(apply.getCertificateType()) + "_" + apply.getStudentNo() + ".pdf";
            String storedName = UUID.randomUUID() + ".pdf";
            Path targetPath = uploadPath.resolve(storedName);
            renderTemplateToPdf(resolveTemplatePath(certificateType), certificateType, studentData, now.toLocalDateTime().toLocalDate(), targetPath);

            Long fileId = idSeq.incrementAndGet();
            jdbcTemplate.update(
                    """
                            INSERT INTO t_file
                            (id, original_name, stored_name, file_path, file_type, file_size, uploader_id, business_type, created_at)
                            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                            """,
                    fileId,
                    originalName,
                    storedName,
                    uploadDir + "/" + storedName,
                    "application/pdf",
                    Files.size(targetPath),
                    (Long) studentData.get("userId"),
                    "certificate",
                    now
            );
            return fileId;
        } catch (IOException e) {
            throw new IllegalStateException("生成证明文件失败: " + e.getMessage(), e);
        }
    }

    private boolean isAutoGeneratedCertificate(String certificateType) {
        String normalized = normalize(certificateType);
        return normalized.contains("党员") || normalized.contains("团员");
    }

    private String resolveTemplatePath(String certificateType) {
        String normalized = normalize(certificateType);
        if (normalized.contains("党员")) {
            return "certificate-templates/party-certificate-template.docx";
        }
        if (normalized.contains("团员") || normalized.contains("团")) {
            return "certificate-templates/league-certificate-template.docx";
        }
        throw new IllegalArgumentException("未找到对应的证明模板");
    }

    private void renderTemplateToPdf(String templatePath, String certificateType, Map<String, Object> studentData, LocalDate issueDate, Path outputPath) throws IOException {
        ClassPathResource resource = new ClassPathResource(templatePath);
        if (!resource.exists()) {
            throw new IllegalArgumentException("模板文件不存在: " + templatePath);
        }
        try (InputStream inputStream = resource.getInputStream();
             XWPFDocument document = new XWPFDocument(inputStream);
             OutputStream outputStream = Files.newOutputStream(outputPath)) {
            renderTemplateToPdf(document, certificateType, studentData, issueDate, outputStream);
        }
    }

    private void renderTemplateToPdf(String templatePath, String certificateType, Map<String, Object> studentData, LocalDate issueDate, OutputStream outputStream) throws IOException {
        ClassPathResource resource = new ClassPathResource(templatePath);
        if (!resource.exists()) {
            throw new IllegalArgumentException("模板文件不存在: " + templatePath);
        }
        try (InputStream inputStream = resource.getInputStream();
             XWPFDocument document = new XWPFDocument(inputStream)) {
            renderTemplateToPdf(document, certificateType, studentData, issueDate, outputStream);
        }
    }

    private void renderTemplateToPdf(XWPFDocument document, String certificateType, Map<String, Object> studentData, LocalDate issueDate, OutputStream outputStream) throws IOException {
        for (XWPFParagraph paragraph : document.getParagraphs()) {
            replaceInParagraph(paragraph, certificateType, studentData, issueDate);
        }
        PdfConverter.getInstance().convert(document, outputStream, createPdfOptions());
    }

    private void replaceInParagraph(XWPFParagraph paragraph, String certificateType, Map<String, Object> studentData, LocalDate issueDate) {
        String text = paragraph.getText();
        if (text == null || text.isBlank()) {
            return;
        }

        String replaced = text;
        if (certificateType.contains("党员")) {
            replaced = replacePartyParagraph(text, studentData, issueDate);
        } else if (certificateType.contains("团员") || certificateType.contains("团")) {
            replaced = replaceLeagueParagraph(text, studentData, issueDate);
        }
        if (replaced.equals(text)) {
            return;
        }
        List<XWPFRun> runs = paragraph.getRuns();
        if (runs == null || runs.isEmpty()) {
            paragraph.createRun().setText(replaced);
            return;
        }

        XWPFRun firstRun = runs.get(0);
        CTR firstCtr = firstRun.getCTR();
        int textCount = firstCtr.sizeOfTArray();
        if (textCount == 0) {
            firstRun.setText(replaced);
        } else {
            firstRun.setText(replaced, 0);
            for (int i = textCount - 1; i >= 1; i--) {
                firstCtr.removeT(i);
            }
        }

        for (int i = runs.size() - 1; i >= 1; i--) {
            paragraph.removeRun(i);
        }
    }

    private String replacePartyParagraph(String text, Map<String, Object> studentData, LocalDate issueDate) {
        if (text.contains("兹证明中国人民大学信息学院")) {
            String name = requiredValue(studentData, "name", "姓名");
            String studentNo = requiredValue(studentData, "studentNo", "学号");
            String idCardNo = requiredValue(studentData, "idCardNo", "身份证号");
            String major = requiredValue(studentData, "major", "专业");
            String grade = requiredValue(studentData, "grade", "年级");
            String educationLevel = requiredValue(studentData, "educationLevel", "培养层次");
            String joinPartyDate = requiredValue(studentData, "joinPartyDate", "入党时间");
            String partyBranchName = requiredValue(studentData, "partyBranchName", "所属党支部");
            return "兹证明中国人民大学信息学院%s，学号：%s，身份证号：%s，为我院%s专业%s级%s生，该生于%s入党，目前组织关系属于中国人民大学信息学院党委%s。"
                    .formatted(name, studentNo, idCardNo, major, grade, educationLevel, joinPartyDate, partyBranchName);
        }
        if (text.contains("202X") || text.contains("202") && text.contains("年") && text.contains("月") && text.contains("日")) {
            return formatDate(issueDate);
        }
        return text;
    }

    private String replaceLeagueParagraph(String text, Map<String, Object> studentData, LocalDate issueDate) {
        if (text.contains("加入中国共产主义青年团")) {
            String name = requiredValue(studentData, "name", "姓名");
            String studentNo = requiredValue(studentData, "studentNo", "学号");
            String idCardNo = requiredValue(studentData, "idCardNo", "身份证号");
            String className = requiredValue(studentData, "className", "班级");
            String joinLeagueDate = requiredValue(studentData, "joinLeagueDate", "入团时间");
            String leagueMemberNo = requiredValue(studentData, "leagueMemberNo", "团员编号");
            return "兹证明中国人民大学信息学院%s，学号：%s，身份证号：%s，为我院%s学生，该生于%s加入中国共产主义青年团，团员编号：%s。"
                    .formatted(name, studentNo, idCardNo, className, joinLeagueDate, leagueMemberNo);
        }
        if (text.contains("202X") || text.contains("202") && text.contains("年") && text.contains("月") && text.contains("日")) {
            return formatDate(issueDate);
        }
        return text;
    }

    private String requiredValue(Map<String, Object> data, String key, String label) {
        String value = stringValue(data.get(key));
        if (value.isBlank()) {
            throw new IllegalArgumentException(label + "缺失，无法生成证明");
        }
        return value;
    }

    private String stringValue(Object value) {
        return value == null ? "" : String.valueOf(value).trim();
    }

    private String blankToEmpty(String value) {
        return value == null ? "" : value.trim();
    }

    private String formatDate(LocalDate date) {
        if (date == null) {
            return "";
        }
        return "%d年%02d月%02d日".formatted(date.getYear(), date.getMonthValue(), date.getDayOfMonth());
    }

    private PdfOptions createPdfOptions() {
        PdfOptions options = PdfOptions.create();
        String pdfFontPath = resolvePdfFontPath();
        if (pdfFontPath == null) {
            return options;
        }
        options.fontProvider(new IFontProvider() {
            @Override
            public Font getFont(String familyName, String encoding, float size, int style, Color color) {
                try {
                    BaseFont baseFont = createBaseFont(pdfFontPath);
                    return new Font(baseFont, size, style, color);
                } catch (Exception e) {
                    return FontFactory.getFont(FontFactory.HELVETICA, size, style, color);
                }
            }
        });
        return options;
    }

    private BaseFont createBaseFont(String fontPath) throws Exception {
        String p = normalize(fontPath);
        if (p.isEmpty()) {
            throw new IllegalArgumentException("字体路径为空");
        }
        if (p.toLowerCase().endsWith(".ttc") && !p.contains(",")) {
            try {
                return BaseFont.createFont(p + ",0", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            } catch (Exception ignore) {
                return BaseFont.createFont(p + ",1", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            }
        }
        return BaseFont.createFont(p, BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
    }

    private String resolvePdfFontPath() {
        String[] candidates = {
                "C:/Windows/Fonts/simfang.ttf",
                "C:/Windows/Fonts/FangSong_GB2312.ttf",
                "C:/Windows/Fonts/simsun.ttc",
                "/usr/share/fonts/opentype/noto/NotoSerifCJK-Regular.ttc",
                "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
                "/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc"
        };
        for (String candidate : candidates) {
            if (Files.exists(Paths.get(candidate))) {
                return candidate;
            }
        }
        return null;
    }

    private String safeFilePart(String value) {
        String normalized = normalize(value);
        if (normalized.isEmpty()) {
            return "certificate";
        }
        return normalized.replaceAll("[\\\\/:*?\"<>|\\s]+", "_");
    }

    private String normalize(String v) {
        return v == null ? "" : v.trim();
    }
}
